#!/bin/bash
echo "enter three
number:"
read a
read b
read c
if [ $a -gt $a ] && [ $a
-gt $c ]
then
largest number"
elif [ $b -gt $a ] && [
$b -gt $c ]
then 
         echo "$b is
largest number"
         echo "$c is
largest number"
fi
